version: '3.4'

services:
  ritabot:
    image: ritabot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DISCORD_TOKEN: MTAwMTczMzAyMTEwOTYwNDQwNA.G747vK.SiLvBo1q1Z9tgTeONvjf-2iYW27aYs0Punlt1s
    ports:
      - 3000:3000
